### PR TITLE
Add Ingrasys S9180 platform

### PR DESCRIPTION
**Pull request by wadelnn**
Add Ingrasys S9180 platform

Signed-off-by: Wade He <chihen.he@gmail.com>

### CODE REVIEW

**Comment by krambn** [comment]
missing directory: sonic-platform-modules-ingrasys?

**Comment by wadelnn** [comment]
It is a submodule  in platform/barefoot/sonic-platform-modules-ingrasys. 
It has to use git command with parameter "--recursive" like "git clone --recursive https://github.com/wadelnn/sonic-buildimage.git -b rel_7_0"

**Comment by krambn** [comment]
Maybe I am missing something here. When I look at the browser I don't see a refpoint.

screen shot 2018-02-22 at 4 33 21 pm

**Comment by krambn** [comment]
Can you give me a refpoint to the sonic-platform-modules-ingrasys repo?
Thanks

**Comment by wadelnn** [comment]
Hi, @krambn 
I updated the submodule path and url.
You can get the refpoint to sonic-platform-modules-ingrasys repo.

**Pull request merged**
